# Generated by Django 3.0.8 on 2020-07-27 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_order_orderstatus_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 27, 11, 53, 13, 330063), verbose_name='Последнее изменение'),
        ),
    ]
